### ISSUE TITLE
pattern option causing Babel to error

### ISSUE THREAD

**Issue by elegua** [babel/babel-brunch#13]
When I use the pattern option I get the following error for each matched file:

```shell
error: - Compiling of 'foo/bar.js' failed. [BABEL] foo/bar.js: Unknown option: pattern ;
```

babel-brunch: 5.1.1
babel-core: 5.4.3

**Comment by es128** [comment]
Odd that the test for this situation is passing. Can you provide an example repo to help me reproduce the error you've observed?

**Comment by es128** [comment]
Nevermind I figured out what's wrong with the test

**Comment by elegua** [comment]
<3

**Comment by es128** [comment]
Thanks for reporting the issue :smile:

**Comment by jblock** [comment]
Whoops! Thanks for fixing my derp :D :tada:
