### ISSUE TITLE
Support configuration for different environments.

### ISSUE THREAD

**Issue by yavorsky** [babel/babel-brunch#51]
Currently, with `.babelrc` you can use the `env` option to set specific options when in a certain environment:

```
{
  "env": {
    "production": {
      "plugins": ["transform-react-constant-elements"]
    }
  },
  "presets": ["es2015"]
}
```
will use preset-es2015 for all envs and add `transform-react-constant-elements` just for prod. 

I'll work on this.

**Comment by denysdovhan** [comment]
Could cause conflicts with #54.

**Comment by yavorsky** [comment]
@denysdovhan why? we just need to support .babelrc (.babelrc.js for Babel 7)
