### ISSUE TITLE
Source maps are mapped to transpiled source

### ISSUE THREAD

**Issue by millerized** [babel/babel-brunch#56]
I've noticed I can't find a way to use the original source instead of the source compiled by babel. 

Is this perhaps a limitation of `babel-brunch` right now or am I missing something in my config somewhere?

Using latest versions of `brunch`, `babel`, and `babel-brunch`.

#### Abbreviated `config`:
```coffee
presets: ['latest']
plugins: [
    'transform-class-properties'
    'transform-object-rest-spread'
    'transform-runtime'
]
```

#### Abbreviated `package.json`:

```json
    "babel-brunch": "^6.1.1",
    "babel-cli": "^6.24.0",
    "babel-plugin-transform-class-properties": "^6.23.0",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.23.0",
    "brunch": "^2.10.9",
```

**Comment by millerized** [comment]
I am not sure that it is related, but I have to use 'inline' for source maps to be mapped properly.
```js
sourceMaps: 'inline'
```

**Comment by denysdovhan** [comment]
I can confirm. Had the same issue.

@shvaikalesh as I know, you're aware of this problem, aren't you?

**Comment by millerized** [comment]
@denysdovhan @shvaikalesh do you believe this is related? https://github.com/brunch/brunch/issues/1635

**Comment by millerized** [comment]
Related: brunch/brunch#1635
