### ISSUE TITLE
babel polyfill included?

### ISSUE THREAD

**Issue by kockok** [babel/babel-brunch#57]
Hello, is [this polyfill package](https://github.com/babel/babel/tree/master/packages/babel-polyfill) included? And, is that possible to also include babel-object-rest-spread?

**Comment by denysdovhan** [comment]
Hi @kockok! Thanks for question 😉 

_babel-brunch_ uses [`babel-preset-env`](https://github.com/babel/babel-preset-env) as default. This preset works like Autoprefixer for your JavaScript.

If you want to include `babel-object-rest-spread` manualy, you can define this plugin in `.babelrc` file or `plugins.babel` field in your `brunch-config.js`.

**Comment by kockok** [comment]
@denysdovhan Thanks for the reply. The question remains that do I need to install/require `babel-polyfill` as well? Or both `babel-polyfill` and `babel-preset-env` just **do the same thing** with different approach?

**Comment by denysdovhan** [comment]
@kockok check `babel-preset-env` docs, [section about `useBuiltIns`](https://github.com/babel/babel-preset-env/blob/master/README.md#usebuiltins). Moreover, the `env`'s description says:

> A Babel preset that can automatically determine the Babel plugins and **_polyfills_** you need based on your supported environments.

That means you shouldn't use `babel-polyfill` additionally.
