### ISSUE TITLE
Publish new npm version

### ISSUE THREAD

**Issue by Anaphase** [babel/babel-brunch#62]
It seems that the package as available on NPM is still using `babel-preset-latest` instead of `babel-preset-env`, and the readme reflects the same incongruences over at https://www.npmjs.com/package/babel-brunch

I'm thinking a new NPM version should be published so that changes made to the repo (5 months ago?) are available on NPM.

**Comment by aptinio** [comment]
@paulmillr, @es128, @kittens any chance we can get a new version up on NPM?

**Comment by rafbgarcia** [comment]
Is this package still active?

**Comment by rafbgarcia** [comment]
FWIW `npm i --save-dev babel-brunch@github:babel/babel-brunch` worked for me
