### ISSUE TITLE
Upgrading to Babel 7

### ISSUE THREAD

**Issue by leofab86** [babel/babel-brunch#65]
Hello, are there any plans to allow upgrading to Babel 7? I saw the pull request and tried to replicate it but getting errors. Are the changes in that pull request working for anyone? Or is there some work-around? I have not been able to find anything online.

**Comment by soumak77** [comment]
@leofab86 you can try my fork by adding the following to your package.json:
```
"babel-brunch": "git+https://github.com/who-are-you-io/babel-brunch.git"
```

**Comment by soumak77** [comment]
@leofab86 also check your local node_modules folder and verify you aren't syncing any babel 6.x libraries.  If you are, you'll need to update the dependencies which are pulling in those libraries to ensure they are working with babel 7.x.
