### ISSUE TITLE
Babel JSX Support: File extension question.

### ISSUE THREAD

**Issue by mattmccray** [babel/babel-brunch#7]
I use Babel's JSX feature in my React project, but I prefer to use a `.jsx` extension on files that are using it to make it clear, at a glance, which files are components (plus I get some nice editor features).

What's the best way to configure babel-brunch / brunch to accept *.jsx files as well as *.js?

**Comment by es128** [comment]
When the plugin was first put together, 6to5 didn't provide jsx support. We'll need to update it to allow the extensions it acts upon to be user-configurable.

Not sure whether jsx should be included as a default as it could mess things up if someone has also installed react-brunch or something else that compiles jsx.

**Comment by jblock** [comment]
I'd vote for keeping `.js` as the default, but letting you pass in a desired extension/regex if you wish to override it. At this point, everyone's doing different stuff (ex: we're using `.es6` for Babel stuff in one of our non-brunch apps), so it might be futile to push everyone in one direction.

I also like the sentiment that anything with a `*.js` file extension should be able to run in the browser as-is, no transformations. Yes, you might end up with a maelstrom of file extensions, but at least you aren't accidentally breaking stuff.

Thoughts? Happy to throw up a PR and take on this work.

**Comment by es128** [comment]
Yes, PR please. 

There are other brunch plugins that allow user-configurable extensions in this way that you could look at. jaded-brunch comes to mind.

**Comment by es128** [comment]
Resolved by #11. Just need to document the option in the readme and publish 5.1.0

**Comment by es128** [comment]
done
